services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: postgres
    container_name: sci_article_db_app
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data